/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore.SearchBook;

import bookstore.Book.Book;
import static bookstore.Database.UserDAO.db;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import org.bson.Document;

/**
 *
 * @author N A T M A N
 */
public class test extends javax.swing.JFrame {

    public static MongoClientURI uri  = new MongoClientURI("mongodb://user01:user01@ds145563.mlab.com:45563/book_shop"); 
    public static MongoClient client = new MongoClient(uri);
    public static MongoDatabase db = client.getDatabase(uri.getDatabase());
    
    /**
     * Creates new form test
     */
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnDeleted = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        addField = new javax.swing.JTextField();
        editField = new javax.swing.JTextField();
        editField1 = new javax.swing.JTextField();
        delField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnAdd.setText("เพิ่ม");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(670, 160, 140, 60);

        btnDeleted.setText("ลบ");
        btnDeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletedActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleted);
        btnDeleted.setBounds(670, 290, 140, 60);

        btnEdit.setText("แก้ไข");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(680, 420, 130, 60);

        addField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFieldMouseClicked(evt);
            }
        });
        addField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFieldActionPerformed(evt);
            }
        });
        getContentPane().add(addField);
        addField.setBounds(450, 160, 190, 50);

        editField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editFieldMouseClicked(evt);
            }
        });
        getContentPane().add(editField);
        editField.setBounds(280, 420, 180, 50);

        editField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editField1MouseClicked(evt);
            }
        });
        editField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editField1ActionPerformed(evt);
            }
        });
        getContentPane().add(editField1);
        editField1.setBounds(480, 420, 180, 50);

        delField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delField1MouseClicked(evt);
            }
        });
        delField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delField1ActionPerformed(evt);
            }
        });
        getContentPane().add(delField1);
        delField1.setBounds(450, 290, 180, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(1200,750);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void addFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFieldActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        MongoCollection<Document> room = db.getCollection("test");
        Document findBook = new Document("name",addField.getText());
        room.insertOne(findBook);
        
//        MongoCursor<Document> cursor = room.find(findBook).iterator();
//         try {
//            while (cursor.hasNext()) {
//                Document doc = cursor.next();
//             
//       
//            }
//        } finally {}
    }//GEN-LAST:event_btnAddActionPerformed

    private void addFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFieldMouseClicked
       addField.setText("");
    }//GEN-LAST:event_addFieldMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       MongoCollection<Document> room = db.getCollection("test");
        Document findBook = new Document("name",editField1.getText());
        room.updateOne(new Document("name",editField.getText()), new Document("$set", new Document("name", editField1.getText())));

    }//GEN-LAST:event_btnEditActionPerformed

    private void editFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editFieldMouseClicked
       editField.setText("");
    }//GEN-LAST:event_editFieldMouseClicked

    private void editField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editField1MouseClicked

    private void editField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editField1ActionPerformed

    private void btnDeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletedActionPerformed
        MongoCollection<Document> room = db.getCollection("test");
        Document findBook = new Document("name",delField1.getText());
        room.deleteOne(new Document("name",delField1.getText()));
    }//GEN-LAST:event_btnDeletedActionPerformed

    private void delField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delField1MouseClicked

    private void delField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addField;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleted;
    private javax.swing.JButton btnEdit;
    private javax.swing.JTextField delField1;
    private javax.swing.JTextField editField;
    private javax.swing.JTextField editField1;
    // End of variables declaration//GEN-END:variables
}
